package gowihi

// https://saratoga-weather.org/wdparser/index.php?site=https%3A%2F%2Fvreme.in.rs%2Fsubotica%2F&submit=Submit
type WeatherDisplayRawData struct {
	// knots
	Wind_speed_avg float64 // current
	// knots
	Wind_speed float64
	// compass; 169 degrees (S)
	Wind_direction float64
	// celsius
	// by default we refer to the outside temperature simply as temperature
	Temperature float64
	// percent
	// similarly "outside humidity" is simply humidity
	Humidity float64
	// hPa
	Barometer float64
	// millimeters
	Cum_rain_daily float64
	Cum_rain_month float64
	Cum_rain_year  float64
	// rain rate mm/min
	Rain_rate     float64
	Rain_rate_max float64
	// celsius
	Indoor_temperature float64
	// percentage
	Indoor_humidity float64
	// icon (integer)
	Forecast_icon int16
	// celsius
	Extra_temp_wmr968 float64
	// percentage
	Extra_hum_wmr968 float64
	// millimeters
	Cum_rain_yest float64
	// celsius (optional)
	Extra_temp_sensor_1 float64
	Extra_temp_sensor_2 float64
	Extra_temp_sensor_3 float64
	Extra_temp_sensor_4 float64
	Extra_temp_sensor_5 float64
	Extra_temp_sensor_6 float64
	Extra_hum_sensor_1  float64
	Extra_hum_sensor_2  float64
	Extra_hum_sensor_3  float64
	// time
	Hour              int16
	Minute            int16
	Seconds           int16 // string
	Station_name_time string
	// integer
	Lightning_count_since_noon int8
	// percentage
	Solar_percentage_of_max float64
	// time
	Day   int8
	Month int8
	// percentage
	Batt_1 float64
	Batt_2 float64
	Batt_3 float64
	Batt_4 float64
	Batt_5 float64
	Batt_6 float64
	Batt_7 float64
	// celsius
	Wind_chill      float64
	Humidex         float64
	Temperature_max float64
	Temperature_min float64
	// icon (integer)
	Curr_condition_icon int16
	// weather description
	Weather_descrip string
	// hPa
	Baro_trend_last_hr float64
	// knots
	Windspeed_hr_1  float64
	Windspeed_hr_2  float64
	Windspeed_hr_3  float64
	Windspeed_hr_4  float64
	Windspeed_hr_5  float64
	Windspeed_hr_6  float64
	Windspeed_hr_7  float64
	Windspeed_hr_8  float64
	Windspeed_hr_9  float64
	Windspeed_hr_10 float64
	Windspeed_hr_11 float64
	Windspeed_hr_12 float64
	Windspeed_hr_13 float64
	Windspeed_hr_14 float64
	Windspeed_hr_15 float64
	Windspeed_hr_16 float64
	Windspeed_hr_17 float64
	Windspeed_hr_18 float64
	Windspeed_hr_19 float64
	Windspeed_hr_20 float64
	Wind_gust_max   float64
	// celsius
	Dewpoint float64
	// feet
	Cloud_height float64
	// date (string)
	Date string
	// celsius
	Humidex_max   float64
	Humidex_min   float64
	Max_windchill float64
	Min_windchill float64
	// number (float)
	Uv float64
	// knots
	Hr_windspeed_1  float64
	Hr_windspeed_2  float64
	Hr_windspeed_3  float64
	Hr_windspeed_4  float64
	Hr_windspeed_5  float64
	Hr_windspeed_6  float64
	Hr_windspeed_7  float64
	Hr_windspeed_8  float64
	Hr_windspeed_9  float64
	Hr_windspeed_10 float64
	// celsius
	Hr_temp_1  float64
	Hr_temp_2  float64
	Hr_temp_3  float64
	Hr_temp_4  float64
	Hr_temp_5  float64
	Hr_temp_6  float64
	Hr_temp_7  float64
	Hr_temp_8  float64
	Hr_temp_9  float64
	Hr_temp_10 float64
	// mm
	Hr_rain_1  float64
	Hr_rain_2  float64
	Hr_rain_3  float64
	Hr_rain_4  float64
	Hr_rain_5  float64
	Hr_rain_6  float64
	Hr_rain_7  float64
	Hr_rain_8  float64
	Hr_rain_9  float64
	Hr_rain_10 float64
	// celsius
	Heat_index_max float64
	Heat_index_min float64
	Heat_index     float64
	// knots
	Max_avg_windspeed_today     float64
	Lightning_counts_last_min   int8
	Time_of_last_lighting_count string
	Date_of_last_lighting_count string
	Wind_avg_direction          float64
	// number
	Nexstorm_distance_last_strike float64
	// compass
	Nexstorm_bearing_last_strike float64
	// celsius
	Extra_temp_sensor_7 float64
	Extra_temp_sensor_8 float64
	// percentage
	Extra_hum_sensor_4 float64
	Extra_hum_sensor_5 float64
	Extra_hum_sensor_6 float64
	Extra_hum_sensor_7 float64
	Extra_hum_sensor_8 float64
	// number (float)
	Vp_solar_vm2 float64
	// celsius
	Indoor_temperature_max float64
	Indoor_temperature_min float64
	// apparent temp
	Apparent_temp float64
	// hPa
	Barometer_max float64
	Barometer_min float64
	// knots
	Max_gust_last_hr float64
	// time
	Max_gust_last_hr_time string
	Max_gust_today_time   string
	// celsius
	Apparent_temp_max float64
	Apparent_temp_min float64
	Dewpoint_max      float64
	Dewpoint_min      float64
	// knots
	Max_gust_in_last_min float64
	// year (int)
	Current_year string
	// celsius
	Thsw_index float64
	// "bool" but (-1/0/1)
	Temp_trend     int8
	Humidity_trend int8
	Humidex_trend  int8
	// compass
	Hr_wind_direction_1  int8
	Hr_wind_direction_2  int8
	Hr_wind_direction_3  int8
	Hr_wind_direction_4  int8
	Hr_wind_direction_5  int8
	Hr_wind_direction_6  int8
	Hr_wind_direction_7  int8
	Hr_wind_direction_8  int8
	Hr_wind_direction_9  int8
	Hr_wind_direction_10 int8
	// number (0-15)
	Vp_leaf_wetness int8
	// number (centibars)
	Vp_soil_moisture float64
	// knots
	Ten_minute_avg_wind_speed float64
	// celsius
	Wet_bulb_temp float64
	// time
	Latitude  float64
	Longitude float64
	// millimeters
	Nine_am_reset_rain_total float64
	// percent
	Daily_high_humditiy float64
	Daily_low_humidity  float64
	// mm
	Midnight_reset_rain_total float64
	// time
	Time_of_daily_low_windchill string
	// watts
	Current_cost_channel_1 float64
	Current_cost_channel_2 float64
	Current_cost_channel_3 float64
	Current_cost_channel_4 float64
	Current_cost_channel_5 float64
	Current_cost_channel_6 float64
	// number (km) (9am or midnight reset)
	Daily_wind_run      float64
	Time_daily_max_temp string
	Time_daily_min_temp string
	// compass
	Ten_minute_avg_wind_direction int8
}

func NewRawWeatherDisplayData() *WeatherDisplayRawData {
	return &WeatherDisplayRawData{
		Wind_speed_avg:                -1.0, // current
		Wind_speed:                    -1.0,
		Wind_direction:                -1.0,
		Temperature:                   -1.0,
		Humidity:                      -1.0,
		Barometer:                     -1.0,
		Cum_rain_daily:                -1.0,
		Cum_rain_month:                -1.0,
		Cum_rain_year:                 -1.0,
		Rain_rate:                     -1.0,
		Rain_rate_max:                 -1.0,
		Indoor_temperature:            -1.0,
		Indoor_humidity:               -1.0,
		Forecast_icon:                 -1,
		Extra_temp_wmr968:             -1.0,
		Extra_hum_wmr968:              -1.0,
		Cum_rain_yest:                 -1.0,
		Extra_temp_sensor_1:           -1.0,
		Extra_temp_sensor_2:           -1.0,
		Extra_temp_sensor_3:           -1.0,
		Extra_temp_sensor_4:           -1.0,
		Extra_temp_sensor_5:           -1.0,
		Extra_temp_sensor_6:           -1.0,
		Extra_hum_sensor_1:            -1.0,
		Extra_hum_sensor_2:            -1.0,
		Extra_hum_sensor_3:            -1.0,
		Hour:                          -1,
		Minute:                        -1,
		Seconds:                       -1,
		Station_name_time:             "uninitialized",
		Lightning_count_since_noon:    -1,
		Solar_percentage_of_max:       -1.0,
		Day:                           -1,
		Month:                         -1,
		Batt_1:                        -1.0,
		Batt_2:                        -1.0,
		Batt_3:                        -1.0,
		Batt_4:                        -1.0,
		Batt_5:                        -1.0,
		Batt_6:                        -1.0,
		Batt_7:                        -1.0,
		Wind_chill:                    -1.0,
		Humidex:                       -1.0,
		Temperature_max:               -1.0,
		Temperature_min:               -1.0,
		Curr_condition_icon:           -1,
		Weather_descrip:               "uninitialized",
		Baro_trend_last_hr:            -1.0,
		Windspeed_hr_1:                -1.0,
		Windspeed_hr_2:                -1.0,
		Windspeed_hr_3:                -1.0,
		Windspeed_hr_4:                -1.0,
		Windspeed_hr_5:                -1.0,
		Windspeed_hr_6:                -1.0,
		Windspeed_hr_7:                -1.0,
		Windspeed_hr_8:                -1.0,
		Windspeed_hr_9:                -1.0,
		Windspeed_hr_10:               -1.0,
		Windspeed_hr_11:               -1.0,
		Windspeed_hr_12:               -1.0,
		Windspeed_hr_13:               -1.0,
		Windspeed_hr_14:               -1.0,
		Windspeed_hr_15:               -1.0,
		Windspeed_hr_16:               -1.0,
		Windspeed_hr_17:               -1.0,
		Windspeed_hr_18:               -1.0,
		Windspeed_hr_19:               -1.0,
		Windspeed_hr_20:               -1.0,
		Wind_gust_max:                 -1.0,
		Dewpoint:                      -1.0,
		Cloud_height:                  -1.0,
		Date:                          "uninitialized",
		Humidex_max:                   -1.0,
		Humidex_min:                   -1.0,
		Max_windchill:                 -1.0,
		Min_windchill:                 -1.0,
		Uv:                            -1.0,
		Hr_windspeed_1:                -1.0,
		Hr_windspeed_2:                -1.0,
		Hr_windspeed_3:                -1.0,
		Hr_windspeed_4:                -1.0,
		Hr_windspeed_5:                -1.0,
		Hr_windspeed_6:                -1.0,
		Hr_windspeed_7:                -1.0,
		Hr_windspeed_8:                -1.0,
		Hr_windspeed_9:                -1.0,
		Hr_windspeed_10:               -1.0,
		Hr_temp_1:                     -1.0,
		Hr_temp_2:                     -1.0,
		Hr_temp_3:                     -1.0,
		Hr_temp_4:                     -1.0,
		Hr_temp_5:                     -1.0,
		Hr_temp_6:                     -1.0,
		Hr_temp_7:                     -1.0,
		Hr_temp_8:                     -1.0,
		Hr_temp_9:                     -1.0,
		Hr_temp_10:                    -1.0,
		Hr_rain_1:                     -1.0,
		Hr_rain_2:                     -1.0,
		Hr_rain_3:                     -1.0,
		Hr_rain_4:                     -1.0,
		Hr_rain_5:                     -1.0,
		Hr_rain_6:                     -1.0,
		Hr_rain_7:                     -1.0,
		Hr_rain_8:                     -1.0,
		Hr_rain_9:                     -1.0,
		Hr_rain_10:                    -1.0,
		Heat_index_max:                -1.0,
		Heat_index_min:                -1.0,
		Heat_index:                    -1.0,
		Max_avg_windspeed_today:       -1.0,
		Lightning_counts_last_min:     -1,
		Time_of_last_lighting_count:   "uninitialized",
		Date_of_last_lighting_count:   "uninitialized",
		Wind_avg_direction:            -1.0,
		Nexstorm_distance_last_strike: -1.0,
		Nexstorm_bearing_last_strike:  -1.0,
		Extra_temp_sensor_7:           -1.0,
		Extra_temp_sensor_8:           -1.0,
		Extra_hum_sensor_4:            -1.0,
		Extra_hum_sensor_5:            -1.0,
		Extra_hum_sensor_6:            -1.0,
		Extra_hum_sensor_7:            -1.0,
		Extra_hum_sensor_8:            -1.0,
		Vp_solar_vm2:                  -1.0,
		Indoor_temperature_max:        -1.0,
		Indoor_temperature_min:        -1.0,
		Apparent_temp:                 -1.0,
		Barometer_max:                 -1.0,
		Barometer_min:                 -1.0,
		Max_gust_last_hr:              -1.0,
		Max_gust_last_hr_time:         "uninitialized",
		Max_gust_today_time:           "uninitialized",
		Apparent_temp_max:             -1.0,
		Apparent_temp_min:             -1.0,
		Dewpoint_max:                  -1.0,
		Dewpoint_min:                  -1.0,
		Max_gust_in_last_min:          -1.0,
		Current_year:                  "uninitialized",
		Thsw_index:                    -1.0,
		Temp_trend:                    -1,
		Humidity_trend:                -1,
		Humidex_trend:                 -1,
		Hr_wind_direction_1:           -1,
		Hr_wind_direction_2:           -1,
		Hr_wind_direction_3:           -1,
		Hr_wind_direction_4:           -1,
		Hr_wind_direction_5:           -1,
		Hr_wind_direction_6:           -1,
		Hr_wind_direction_7:           -1,
		Hr_wind_direction_8:           -1,
		Hr_wind_direction_9:           -1,
		Hr_wind_direction_10:          -1,
		Vp_leaf_wetness:               -1,
		Vp_soil_moisture:              -1.0,
		Ten_minute_avg_wind_speed:     -1.0,
		Wet_bulb_temp:                 -1.0,
		Latitude:                      -1.0,
		Longitude:                     -1.0,
		Nine_am_reset_rain_total:      -1.0,
		Daily_high_humditiy:           -1.0,
		Daily_low_humidity:            -1.0,
		Midnight_reset_rain_total:     -1.0,
		Time_of_daily_low_windchill:   "uninitialized",
		Current_cost_channel_1:        -1.0,
		Current_cost_channel_2:        -1.0,
		Current_cost_channel_3:        -1.0,
		Current_cost_channel_4:        -1.0,
		Current_cost_channel_5:        -1.0,
		Current_cost_channel_6:        -1.0,
		Daily_wind_run:                -1.0,
		Time_daily_max_temp:           "uninitialized",
		Time_daily_min_temp:           "uninitialized",
		Ten_minute_avg_wind_direction: -1,
	}
}
